workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_CHANNEL: stable
        FLUTTER_VERSION: 3.19.6

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          # حذف ملف القفل القديم لتجنب التعارض
          rm -f Podfile.lock 
          # تحديث مستودع CocoaPods وتنزيل التبعيات الجديدة
          pod install --repo-update
          cd ..

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: YP6MHFSJ8
        issuer_id: 3ce6e981-87e0-4391-82e7-c5bbc030e2934
