workflows:
  ios-build:
    name: iOS Build
    environment:

      cocoapods: 1.16.2  # نسخة حديثة من CocoaPods
      flutter: 3.38.1    # نسخة Flutter
    scripts:
      - name: Pre-build cleanup and dependencies
        script: |
          # تنظيف المشروع
          flutter clean
          flutter pub get
          
          # تحديث CocoaPods وإعادة تثبيت الـ pods مع إجبار تحديث GoogleMaps
          cd ios
          rm -rf Pods Podfile.lock
          pod repo update
          pod install
          pod update GoogleMaps
      

      - name: Build iOS IPA
        script: |
          flutter build ipa --release
    

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        key_id: YP6MHFSJ8
        issuer_id: 3ce6e981-87e0-4391-82e7-c5bbc030e2934
