class RestAreas {
   String name;
   String location;
   String areaType;
    double price;
    double totalSpace;
    double internalSpace;
    int maxGuests;
    int numDoubleBeds;
    int numSingleBeds;
    int numHalls;
    int numBedrooms;
    int numFloors;
    int numBathroomsIndoor;
    int numBathroomsOutdoor;
    bool kitchenAvailable;
    List<String> kitchenContents;
    bool hasAcHeating;
   bool tvScreens;
    bool freeWifi;
    List<String> entertainmentGames;
    double outdoorSpace;
    double grassSpace;
    String poolType;
    double poolSpace;
    double poolDepth;
    bool poolHeating;
   bool poolFilter;
    bool garage;
   bool outdoorSeating;
   bool childrenGames;
    bool outdoorKitchen;
    bool slaughterPlace;
    bool well;
    bool powerGenerator;
    bool outdoorBathroom;
    String otherSpecs;
    String hostId;
    String mainImage;
    List<String> detailsImages;
    double rating;
    String description;
    String geoArea;
    String contactNumber;
    String cityId;
    String checkInTime;
    String checkOutTime;

  RestAreas({
    required this.name,
    required this.location,
    required this.areaType,
    required this.price,
    required this.totalSpace,
    required this.internalSpace,
    required this.maxGuests,
    required this.numDoubleBeds,
    required this.numSingleBeds,
    required this.numHalls,
    required this.numBedrooms,
    required this.numFloors,
    required this.numBathroomsIndoor,
    required this.numBathroomsOutdoor,
    required this.kitchenAvailable,
    required this.kitchenContents,
    required this.hasAcHeating,
    required this.tvScreens,
    required this.freeWifi,
    required this.entertainmentGames,
    required this.outdoorSpace,
    required this.grassSpace,
    required this.poolType,
    required this.poolSpace,
    required this.poolDepth,
    required this.poolHeating,
    required this.poolFilter,
    required this.garage,
    required this.outdoorSeating,
    required this.childrenGames,
    required this.outdoorKitchen,
    required this.slaughterPlace,
    required this.well,
    required this.powerGenerator,
    required this.outdoorBathroom,
    required this.otherSpecs,
    required this.hostId,
    required this.mainImage,
    required this.detailsImages,
    required this.rating,
    required this.description,
    required this.geoArea,
    required this.contactNumber,
    required this.cityId,
    required this.checkInTime,
    required this.checkOutTime,
  });

// يمكنك إضافة دوال لتسهيل التحويل إلى JSON أو من JSON هنا إذا لزم الأمر
}